project:
  type: website
  output-dir: docs

website:
  title: "My Blogs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/gayatribkar
      - icon: linkedin
        href: https://www.linkedin.com/in/gayatri-bhatambarekar/
format:
  html:
    theme: cosmo
    css: styles.css



